version: '3.9'
services:
  postgres:
    container_name: fb-stats
    image: postgres:15.7-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
